site_name: The Engineering Collective
nav: 
    - Home: index.md    
    - Using This Collective: how-to-use.md
    - Quests: 
        - 'Quests' : 'quests/index.md'
        - 'Java Quest' : 'quests/java/index.md'
        - 'React Quest' : 'quests/react/index.md'   
    - Contributing: contributing.md

theme:
    name: 'material'
    

