site_name: The Engineering Collective
nav: 
    - Home: index.md    
    - Using This Collective: how-to-use.md
    - Quests: 
        - 'Quests' : 'quests/index.md'
        - 'Java Engineer' : 'quests/java-engineer/index.md'
        - 'React Engineer' : 'quests/react-engineer/index.md'   
    - Contributing: contributing.md

theme:
    name: 'material'
    

